version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    links:
      - backend
    environment:
      WAIT_HOSTS: backend:8081